---
- name: Set JAVA_HOME
  shell: export JAVA_HOME=/usr/share/elasticsearch/jdk

- name: Define JAVA_HOME in PATH
  shell: export PATH=$PATH:/usr/share/elasticsearch/jdk/bin

- name: Include OS Specific setup tasks
  include: setup-{{ ansible_os_family }}.yml

- include: config.yml
- include: ssl.yml
- include: plugins.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
    enabled: "{{ logstash_enabled_on_boot }}"
