- hosts: elastic-01
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "silveira"
      cluster.initial_master_nodes: "elastic-01,elastic-02,elastic-03"
      discovery.seed_hosts: "elastic-01,elastic-02,elastic-03"
      http.port: 9200
      bootstrap.memory_lock: false

- hosts: elastic-02
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "silveira"
      cluster.initial_master_nodes: "elastic-01,elastic-02,elastic-03"
      discovery.seed_hosts: "elastic-01,elastic-02,elastic-03"
      http.port: 9200
      bootstrap.memory_lock: false

- hosts: elastic-03
  roles:
    - role: elastic.elasticsearch
  vars:
    es_heap_size: "1g"
    es_config:
      cluster.name: "silveira"
      cluster.initial_master_nodes: "elastic-01,elastic-02,elastic-03"
      discovery.seed_hosts: "elastic-01,elastic-02,elastic-03"
      http.port: 9200
      bootstrap.memory_lock: false